### ISSUE TITLE
"Kredite" return `404`

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-instance-sicprod#183]
when eg looking at [Sigmund](https://sicprod.acdh.oeaw.ac.at/en/detail/person/18) there are a lot of loans ("Kredite") involved. But due to the limitation of the queryset to some types [here](https://github.com/acdh-oeaw/apis-instance-sicprod/blob/7f7705c472737788e21e354060bffa4eea1cdf09/apis_ontology/querysets.py#L2) these always return `404`

**Comment by b1rger** [comment]
fixed in 5a299dcf7fef3503e237ef39d83e3a7c7f349564
