### ISSUE TITLE
Add /apis_ontology.[model]/{id}/ endpoints to Swagger 

### ISSUE THREAD

**Issue by katharinawuensche** [acdh-oeaw/apis-instance-sicprod#83]
The following endpoints seem to be missing in the Swagger documentation:

- [ ] apis/api/apis_ontology.event/{id}
- [ ] apis/api/apis_ontology.function/{id}
- [ ] apis/api/apis_ontology.institution/{id}
- [ ] apis/api/apis_ontology.person/{id}
- [ ] apis/api/apis_ontology.place/{id}
- [ ] apis/api/apis_ontology.salary/{id}

Their response should be a single entry with the same fields as in the list view + a list of relations grouped by class.

**Comment by b1rger** [comment]
I've extended the endpoint enumerator to include those endpoints. Can you check if that works for you?

**Comment by ctot-nondef** [comment]
@b1rger if you like you can also re-run the [frontend-build](https://github.com/acdh-oeaw/sicprod-nuxt/actions/runs/9127699371) yourself to check ;)

**Comment by b1rger** [comment]
> > a list of relations grouped by class.
> 
> this seems to be missing from both the swagger dok as well as the return shape

ah, yeah, I was referring to the endpoints in the swagger documentation. I've created #85 for tracking the detail responses shapes
