### ISSUE TITLE
Detail responses

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-instance-sicprod#85]
From #83:

> Their response should be a single entry with the same fields as in the list view + a list of relations grouped by class.

**Comment by b1rger** [comment]
We (@katharinawuensche and I) discussed moving the relations to a separate endpoint (i.e. `{id}/relations`), because there can be **a lot** of relations for an entity. The separate endpoint would have a paginated result, but not grouped by relation class (but we can add a `relations` list to the detail view that lists existing relation types). I guess this would replace 

> a list of relations grouped by class

?

CC @ctot-nondef

**Comment by b1rger** [comment]
from #83:

>>   a list of relations grouped by class.
>
> this seems to be missing from both the swagger dok as well as the return shape

I can see relation in https://sicprod.acdh-dev.oeaw.ac.at/apis/api/apis_ontology.event/17/ and https://sicprod.acdh-dev.oeaw.ac.at/apis/api/apis_ontology.place/28/ and https://sicprod.acdh-dev.oeaw.ac.at/apis/api/apis_ontology.person/16/  - so I'm not sure exactly whats missing?

**Comment by ctot-nondef** [comment]
got it, in that case the requests in issue #83 are somewhat outdated and parts of the frontend code need to be rewritten

the endpoints behave according in line with the available documentation, will leave this open for @katharinawuensche to check, thank you!
